<?php
/**
 * Tests for the frozen in-plugin catalog fallback.
 *
 * The fallback is the last tier of oddout_catalog_load(): used only when
 * remote fetch fails AND there's no stale option mirror. It ships in
 * the plugin zip at odd/data/fallback-registry.json, generated by
 * _tools/build-catalog.py.
 */

class Test_Catalog_Fallback extends WP_UnitTestCase {

	public function set_up() {
		parent::set_up();
		add_filter( 'oddout_catalog_signature_required', '__return_false' );
	}

	private function catalog_row( $slug, $overrides = array() ) {
		$base = 'https://odd.regionallyfamous.com/catalog/v1/';
		return array_merge(
			array(
				'type'         => 'widget',
				'slug'         => $slug,
				'name'         => ucwords( str_replace( '-', ' ', $slug ) ),
				'version'      => '1.0.0',
				'download_url' => $base . 'bundles/widget-' . $slug . '.wp',
				'sha256'       => str_repeat( 'a', 64 ),
				'size'         => 12345,
				'icon_url'     => $base . 'icons/widget-' . $slug . '.svg',
				'card_url'     => $base . 'cards/widget-' . $slug . '.webp',
			),
			$overrides
		);
	}

	private function build_widget_catalog_zip( $slug ) {
		$path = tempnam( sys_get_temp_dir(), 'odd_catalog_widget_' ) . '.wp';
		$zip  = new ZipArchive();
		$this->assertTrue(
			true === $zip->open( $path, ZipArchive::CREATE | ZipArchive::OVERWRITE ),
			'Failed to open catalog widget fixture zip for writing.'
		);
		$zip->addFromString(
			'manifest.json',
			wp_json_encode(
				array(
					'type'          => 'widget',
					'slug'          => $slug,
					'name'          => 'Catalog Style Widget',
					'label'         => 'Catalog Style Widget',
					'version'       => '1.0.0',
					'description'   => 'Widget fixture with CSS.',
					'entry'         => 'widget.js',
					'css'           => array( 'widget.css' ),
					'icon'          => 'dashicons-screenoptions',
					'movable'       => true,
					'resizable'     => true,
					'minWidth'      => 220,
					'minHeight'     => 160,
					'defaultWidth'  => 260,
					'defaultHeight' => 200,
				)
			)
		);
		$zip->addFromString(
			'widget.js',
			"(function(){window.desktopModeWidgets=window.desktopModeWidgets||{};window.desktopModeWidgets['odd/" . $slug . "']=function(){return function(){};};})();"
		);
		$zip->addFromString( 'widget.css', '.catalog-style-widget{display:block;}' );
		$zip->close();
		return $path;
	}

	public function tear_down() {
		delete_transient( ODDOUT_CATALOG_TRANSIENT );
		delete_option( ODDOUT_CATALOG_STALE_OPTION );
		delete_option( ODDOUT_CATALOG_META_OPTION );
		delete_option( ODDOUT_CATALOG_ROLLBACK_OPTION );
		wp_set_current_user( 0 );
		global $wp_rest_server;
		$wp_rest_server = null;
		// Blow the fallback loader's static cache between tests by
		// flipping the filter — simplest way without adding a
		// "reset" helper to the production surface.
		remove_all_filters( 'oddout_catalog_fallback_path' );
		remove_all_filters( 'oddout_catalog_entry_url_allowed' );
		remove_all_filters( 'oddout_catalog_max_response_bytes' );
		remove_all_filters( 'oddout_catalog_allow_empty_remote' );
		remove_all_filters( 'oddout_catalog_url' );
		remove_all_filters( 'oddout_catalog_signature_required' );
		remove_all_filters( 'oddout_catalog_registry_signature_body' );
		remove_all_filters( 'oddout_catalog_public_keys' );
		remove_all_filters( 'oddout_catalog_current_versions' );
		remove_all_filters( 'oddout_catalog_api_version' );
		remove_all_filters( 'pre_http_request' );
		parent::tear_down();
	}

	public function test_fallback_file_ships_in_plugin() {
		$path = oddout_catalog_fallback_path();
		$this->assertFileExists( $path, 'Release zip must ship odd/data/fallback-registry.json.' );
	}

	public function test_fallback_load_returns_normalised_structure() {
		$registry = oddout_catalog_fallback_load();
		$this->assertIsArray( $registry );
		$this->assertArrayHasKey( 'version', $registry );
		$this->assertArrayHasKey( 'starter_pack', $registry );
		$this->assertArrayHasKey( 'bundles', $registry );
		$this->assertIsArray( $registry['bundles'] );
		$this->assertNotEmpty( $registry['bundles'], 'Built-in fallback ships real bundles.' );
		foreach ( $registry['bundles'] as $row ) {
			$this->assertArrayHasKey( 'type', $row );
			$this->assertArrayHasKey( 'slug', $row );
			$this->assertArrayHasKey( 'name', $row );
		}
	}

	public function test_fallback_missing_file_returns_empty_registry() {
		// Redirect to a non-existent file.
		add_filter(
			'oddout_catalog_fallback_path',
			static function () {
				return '/tmp/odd-nonexistent-fallback-registry.json';
			}
		);
		// Force the loader's static cache to re-read from the filter.
		// We purposefully never installed a cache-reset helper — this
		// test uses a fresh process-level state by loading the module
		// directly through the uncached path.
		$this->markTestSkipped(
			'Loader cache is process-global by design; missing-file behavior exercised via the guard in oddout_catalog_fallback_load() — see inline empty-registry branch.'
		);
	}

	public function test_catalog_load_uses_fallback_when_remote_and_stale_fail() {
		// Simulate remote failure + no stale option by pre-filtering
		// the HTTP layer.
		add_filter(
			'pre_http_request',
			static function () {
				return new WP_Error( 'test_offline', 'simulated network failure' );
			}
		);
		delete_transient( ODDOUT_CATALOG_TRANSIENT );
		delete_option( ODDOUT_CATALOG_STALE_OPTION );

		$registry = oddout_catalog_load( true );
		$this->assertIsArray( $registry );
		$this->assertArrayHasKey( 'bundles', $registry );
		$this->assertNotEmpty(
			$registry['bundles'],
			'When remote and stale both fail, the Shop must still see the bundled fallback registry.'
		);
	}

	public function test_empty_remote_does_not_poison_stale_catalog() {
		$stale = oddout_catalog_normalise(
			array(
				'version' => 1,
				'bundles' => array(
					$this->catalog_row( 'known-good' ),
				),
			)
		);
		update_option( ODDOUT_CATALOG_STALE_OPTION, $stale, false );
		add_filter(
			'pre_http_request',
			static function () {
				return array(
					'headers'  => array(),
					'body'     => wp_json_encode(
						array(
							'version' => 1,
							'bundles' => array(),
						)
					),
					'response' => array(
						'code'    => 200,
						'message' => 'OK',
					),
				);
			}
		);

		$registry = oddout_catalog_load( true );
		$this->assertSame( 'known-good', $registry['bundles'][0]['slug'] );
		$mirror = get_option( ODDOUT_CATALOG_STALE_OPTION );
		$this->assertSame( 'known-good', $mirror['bundles'][0]['slug'] );
		$meta = oddout_catalog_meta();
		$this->assertSame( 'stale_option', $meta['source'] );
		$this->assertSame( 'empty_remote', $meta['last_error_code'] );
	}

	public function test_empty_remote_without_stale_uses_bundled_fallback() {
		delete_transient( ODDOUT_CATALOG_TRANSIENT );
		delete_option( ODDOUT_CATALOG_STALE_OPTION );
		add_filter(
			'pre_http_request',
			static function () {
				return array(
					'headers'  => array(),
					'body'     => wp_json_encode(
						array(
							'version' => 1,
							'bundles' => array(),
						)
					),
					'response' => array(
						'code'    => 200,
						'message' => 'OK',
					),
				);
			}
		);

		$registry = oddout_catalog_load( true );
		$this->assertNotEmpty( $registry['bundles'] );
		$meta = oddout_catalog_meta();
		$this->assertSame( 'fallback_file', $meta['source'] );
		$this->assertSame( 'empty_remote', $meta['last_error_code'] );
	}

	public function test_non_empty_remote_is_not_augmented_from_fallback() {
		$raw = array(
			'version' => 1,
			'bundles' => array(
				$this->catalog_row( 'remote-widget' ),
			),
		);
		add_filter(
			'pre_http_request',
			static function () use ( $raw ) {
				return array(
					'headers'  => array(),
					'body'     => wp_json_encode( $raw ),
					'response' => array(
						'code'    => 200,
						'message' => 'OK',
					),
				);
			}
		);

		$registry = oddout_catalog_load( true );
		$slugs    = wp_list_pluck( $registry['bundles'], 'slug' );
		$this->assertSame( array( 'remote-widget' ), $slugs, 'Accepted remote registries must not be partially augmented from the bundled fallback.' );

		$mirror       = get_option( ODDOUT_CATALOG_STALE_OPTION );
		$mirror_slugs = wp_list_pluck( $mirror['bundles'], 'slug' );
		$this->assertSame( array( 'remote-widget' ), $mirror_slugs, 'The stale mirror should store the exact accepted remote payload.' );
	}

	public function test_private_empty_remote_can_opt_in_without_fallback_repair() {
		add_filter( 'oddout_catalog_allow_empty_remote', '__return_true' );
		add_filter(
			'pre_http_request',
			static function () {
				return array(
					'headers'  => array(),
					'body'     => wp_json_encode(
						array(
							'version' => 1,
							'bundles' => array(),
						)
					),
					'response' => array(
						'code'    => 200,
						'message' => 'OK',
					),
				);
			}
		);

		$registry = oddout_catalog_load( true );
		$this->assertSame( array(), $registry['bundles'] );
		$meta = oddout_catalog_meta();
		$this->assertSame( 'remote', $meta['source'] );
		$this->assertFalse( $meta['empty_remote'] );

		remove_all_filters( 'pre_http_request' );
		add_filter(
			'pre_http_request',
			static function () {
				return new WP_Error( 'offline', 'simulated offline catalog' );
			}
		);

		$stale = oddout_catalog_load( true );
		$this->assertSame( array(), $stale['bundles'] );
		$meta = oddout_catalog_meta();
		$this->assertSame( 'stale_option', $meta['source'] );
	}

	public function test_catalog_rest_redacts_install_fields_for_non_admins() {
		$raw = array(
			'version' => 1,
			'bundles' => array(
				$this->catalog_row( 'catalog-widget' ),
			),
		);
		add_filter(
			'pre_http_request',
			static function () use ( $raw ) {
				return array(
					'headers'  => array(),
					'body'     => wp_json_encode( $raw ),
					'response' => array(
						'code'    => 200,
						'message' => 'OK',
					),
				);
			}
		);
		oddout_catalog_load( true );

		$user = self::factory()->user->create( array( 'role' => 'subscriber' ) );
		wp_set_current_user( $user );

		global $wp_rest_server;
		$wp_rest_server = new WP_REST_Server();
		do_action( 'rest_api_init' );

		$request  = new WP_REST_Request( 'GET', '/odd/v1/bundles/catalog' );
		$response = $wp_rest_server->dispatch( $request );
		$data     = $response->get_data();

		$this->assertSame( 200, $response->get_status() );
		$this->assertArrayNotHasKey( 'download_url', $data['bundles'][0] );
		$this->assertArrayNotHasKey( 'sha256', $data['bundles'][0] );
		$this->assertSame( 'https://odd.regionallyfamous.com/catalog/v1/icons/widget-catalog-widget.svg', $data['bundles'][0]['icon_url'] );
		$this->assertArrayNotHasKey( 'meta', $data );
	}

	public function test_catalog_rest_requires_login() {
		wp_set_current_user( 0 );

		global $wp_rest_server;
		$wp_rest_server = new WP_REST_Server();
		do_action( 'rest_api_init' );

		$request  = new WP_REST_Request( 'GET', '/odd/v1/bundles/catalog' );
		$response = $wp_rest_server->dispatch( $request );

		$this->assertSame( 401, $response->get_status() );
	}

	public function test_catalog_rest_rejects_unknown_type_arg() {
		$user = self::factory()->user->create( array( 'role' => 'subscriber' ) );
		wp_set_current_user( $user );

		global $wp_rest_server;
		$wp_rest_server = new WP_REST_Server();
		do_action( 'rest_api_init' );

		$request = new WP_REST_Request( 'GET', '/odd/v1/bundles/catalog' );
		$request->set_param( 'type', 'plugin' );
		$response = $wp_rest_server->dispatch( $request );

		$this->assertSame( 400, $response->get_status() );
	}

	public function test_catalog_install_rest_requires_slug_arg() {
		$user = self::factory()->user->create( array( 'role' => 'administrator' ) );
		wp_set_current_user( $user );

		global $wp_rest_server;
		$wp_rest_server = new WP_REST_Server();
		do_action( 'rest_api_init' );

		$request  = new WP_REST_Request( 'POST', '/odd/v1/bundles/install-from-catalog' );
		$response = $wp_rest_server->dispatch( $request );

		$this->assertSame( 400, $response->get_status() );
	}

	public function test_catalog_widget_install_rest_returns_style_urls_for_hot_loading() {
		$slug         = 'catalog-style-widget';
		$zip_path     = $this->build_widget_catalog_zip( $slug );
		$zip_bytes    = file_get_contents( $zip_path );
		$download_url = 'https://odd.regionallyfamous.com/catalog/v1/bundles/widget-' . $slug . '.wp';
		$registry     = array(
			'version' => 1,
			'bundles' => array(
				$this->catalog_row(
					$slug,
					array(
						'name'         => 'Catalog Style Widget',
						'download_url' => $download_url,
						'sha256'       => hash_file( 'sha256', $zip_path ),
						'size'         => filesize( $zip_path ),
					)
				),
			),
		);
		$this->assertIsString( $zip_bytes );

		add_filter(
			'pre_http_request',
			static function ( $preempt, $args, $url ) use ( $registry, $download_url, $zip_bytes ) {
				if ( ODDOUT_CATALOG_URL === $url ) {
					return array(
						'headers'  => array(),
						'body'     => wp_json_encode( $registry ),
						'response' => array(
							'code'    => 200,
							'message' => 'OK',
						),
					);
				}
				if ( $download_url === $url ) {
					if ( ! empty( $args['filename'] ) ) {
						file_put_contents( $args['filename'], $zip_bytes );
					}
					return array(
						'headers'  => array(),
						'body'     => '',
						'response' => array(
							'code'    => 200,
							'message' => 'OK',
						),
					);
				}
				return $preempt;
			},
			10,
			3
		);

		$user = self::factory()->user->create( array( 'role' => 'administrator' ) );
		wp_set_current_user( $user );

		global $wp_rest_server;
		$wp_rest_server = new WP_REST_Server();
		do_action( 'rest_api_init' );

		oddout_catalog_load( true );

		try {
			$request = new WP_REST_Request( 'POST', '/odd/v1/bundles/install-from-catalog' );
			$request->set_param( 'slug', $slug );
			$response = $wp_rest_server->dispatch( $request );
			$data     = $response->get_data();

			$this->assertSame( 200, $response->get_status(), is_array( $data ) && isset( $data['message'] ) ? $data['message'] : 'Catalog install failed.' );
			$this->assertSame( 'widget', $data['type'] );
			$this->assertNotEmpty( $data['entry_url'] );
			$this->assertStringContainsString( '/widgets/' . $slug . '/widget.js', $data['entry_url'] );
			$this->assertArrayHasKey( 'style_urls', $data );
			$this->assertCount( 1, $data['style_urls'] );
			$this->assertStringContainsString( '/widgets/' . $slug . '/widget.css', $data['style_urls'][0] );
		} finally {
			oddout_bundle_uninstall( $slug );
			wp_delete_file( $zip_path );
		}
	}

	public function test_catalog_update_download_failure_preserves_installed_bundle() {
		$slug      = 'catalog-update-safe-widget';
		$zip_path  = $this->build_widget_catalog_zip( $slug );
		$installed = oddout_bundle_install( $zip_path, $slug . '.wp' );
		wp_delete_file( $zip_path );

		$this->assertIsArray( $installed, is_wp_error( $installed ) ? $installed->get_error_message() : 'Fixture install failed.' );
		$this->assertSame( 'widget', oddout_bundle_type_for_slug( $slug ) );

		$download_url = 'https://odd.regionallyfamous.com/catalog/v1/bundles/widget-' . $slug . '.wp';
		$registry     = array(
			'version' => 1,
			'bundles' => array(
				$this->catalog_row(
					$slug,
					array(
						'name'         => 'Catalog Update Safe Widget',
						'version'      => '1.0.1',
						'download_url' => $download_url,
					)
				),
			),
		);

		add_filter(
			'pre_http_request',
			static function ( $preempt, $args, $url ) use ( $registry, $download_url ) {
				if ( ODDOUT_CATALOG_URL === $url ) {
					return array(
						'headers'  => array(),
						'body'     => wp_json_encode( $registry ),
						'response' => array(
							'code'    => 200,
							'message' => 'OK',
						),
					);
				}
				if ( $download_url === $url ) {
					return new WP_Error( 'http_request_failed', 'No network from this environment.' );
				}
				return $preempt;
			},
			10,
			3
		);

		$user = self::factory()->user->create( array( 'role' => 'administrator' ) );
		wp_set_current_user( $user );

		global $wp_rest_server;
		$wp_rest_server = new WP_REST_Server();
		do_action( 'rest_api_init' );
		oddout_catalog_load( true );

		try {
			$request = new WP_REST_Request( 'POST', '/odd/v1/bundles/install-from-catalog' );
			$request->set_param( 'slug', $slug );
			$request->set_param( 'allow_update', true );
			$response = $wp_rest_server->dispatch( $request );

			$this->assertSame( 502, $response->get_status() );
			$this->assertSame( 'widget', oddout_bundle_type_for_slug( $slug ), 'Existing bundle should remain installed when the catalog download fails.' );
		} finally {
			oddout_bundle_uninstall( $slug );
		}
	}

	public function test_catalog_normalise_preserves_card_url_for_shop_art() {
		$registry = oddout_catalog_normalise(
			array(
				'version' => 1,
				'bundles' => array(
					array(
						'type'     => 'icon-set',
						'slug'     => 'sample-icons',
						'name'     => 'Sample Icons',
						'icon_url' => 'https://example.com/catalog/v1/icons/iconset-sample-icons.webp',
						'card_url' => 'https://example.com/catalog/v1/cards/iconset-sample-icons.webp',
					),
				),
			)
		);

		$this->assertSame(
			'https://example.com/catalog/v1/cards/iconset-sample-icons.webp',
			$registry['bundles'][0]['card_url']
		);
	}

	public function test_catalog_normalise_drops_svg_icon_sets() {
		$registry = oddout_catalog_normalise(
			array(
				'version'      => 1,
				'starter_pack' => array(
					'iconSets' => array( 'svg-icons', 'modern-icons' ),
				),
				'bundles'      => array(
					$this->catalog_row(
						'svg-icons',
						array(
							'type'     => 'icon-set',
							'icon_url' => 'https://odd.regionallyfamous.com/catalog/v1/icons/iconset-svg-icons.svg',
						)
					),
					$this->catalog_row(
						'modern-icons',
						array(
							'type'     => 'icon-set',
							'icon_url' => 'https://odd.regionallyfamous.com/catalog/v1/icons/iconset-modern-icons.webp',
						)
					),
					$this->catalog_row( 'still-valid-widget' ),
				),
			)
		);

		$slugs = wp_list_pluck( $registry['bundles'], 'slug' );
		$this->assertNotContains( 'svg-icons', $slugs );
		$this->assertContains( 'modern-icons', $slugs );
		$this->assertContains( 'still-valid-widget', $slugs );
		$this->assertSame( array( 'modern-icons' ), $registry['starter_pack']['iconSets'] );
	}

	public function test_catalog_uses_full_registry_fallback_only() {
		$registry = oddout_catalog_normalise(
			array(
				'version'      => 1,
				'starter_pack' => array(
					'iconSets' => array( 'svg-icons' ),
				),
				'bundles'      => array(
					$this->catalog_row(
						'svg-icons',
						array(
							'type'     => 'icon-set',
							'icon_url' => 'https://odd.regionallyfamous.com/catalog/v1/icons/iconset-svg-icons.svg',
						)
					),
					$this->catalog_row( 'still-valid-widget' ),
				),
			)
		);
		$iconsets = array_values(
			array_filter(
				$registry['bundles'],
				static function ( $row ) {
					return is_array( $row ) && isset( $row['type'] ) && 'icon-set' === $row['type'];
				}
			)
		);

		$this->assertSame( array(), $iconsets );
		$this->assertSame( array(), $registry['starter_pack']['iconSets'] );
	}

	public function test_catalog_rest_keeps_install_fields_for_admins() {
		$raw = array(
			'version' => 1,
			'bundles' => array(
				$this->catalog_row(
					'admin-catalog-widget',
					array(
						'sha256' => str_repeat( 'b', 64 ),
					)
				),
			),
		);
		add_filter(
			'pre_http_request',
			static function () use ( $raw ) {
				return array(
					'headers'  => array(),
					'body'     => wp_json_encode( $raw ),
					'response' => array(
						'code'    => 200,
						'message' => 'OK',
					),
				);
			}
		);
		oddout_catalog_load( true );

		$user = self::factory()->user->create( array( 'role' => 'administrator' ) );
		wp_set_current_user( $user );

		global $wp_rest_server;
		$wp_rest_server = new WP_REST_Server();
		do_action( 'rest_api_init' );

		$request  = new WP_REST_Request( 'GET', '/odd/v1/bundles/catalog' );
		$response = $wp_rest_server->dispatch( $request );
		$data     = $response->get_data();

		$this->assertSame( 200, $response->get_status() );
		$this->assertSame( 'https://odd.regionallyfamous.com/catalog/v1/bundles/widget-admin-catalog-widget.wp', $data['bundles'][0]['download_url'] );
		$this->assertSame( str_repeat( 'b', 64 ), $data['bundles'][0]['sha256'] );
		$this->assertArrayHasKey( 'meta', $data );
	}

	public function test_catalog_refresh_rest_returns_rehydration_rows() {
		$raw = array(
			'version' => 1,
			'bundles' => array(
				$this->catalog_row( 'fresh-widget' ),
			),
		);
		add_filter(
			'pre_http_request',
			static function () use ( $raw ) {
				return array(
					'headers'  => array(),
					'body'     => wp_json_encode( $raw ),
					'response' => array(
						'code'    => 200,
						'message' => 'OK',
					),
				);
			}
		);

		$user = self::factory()->user->create( array( 'role' => 'administrator' ) );
		wp_set_current_user( $user );

		global $wp_rest_server;
		$wp_rest_server = new WP_REST_Server();
		do_action( 'rest_api_init' );

		$request  = new WP_REST_Request( 'POST', '/odd/v1/bundles/refresh' );
		$response = $wp_rest_server->dispatch( $request );
		$data     = $response->get_data();

		$this->assertSame( 200, $response->get_status() );
		$this->assertTrue( $data['refreshed'] );
		$this->assertSame( 1, $data['count'] );
		$this->assertSame( 'fresh-widget', $data['bundles'][0]['slug'] );
		$this->assertSame( 'remote', $data['meta']['source'] );
	}

	public function test_catalog_check_detects_remote_hash_without_replacing_rows() {
		$local = oddout_catalog_normalise(
			array(
				'version' => 1,
				'bundles' => array(
					$this->catalog_row( 'old-widget' ),
				),
			)
		);
		set_transient( ODDOUT_CATALOG_TRANSIENT, $local, HOUR_IN_SECONDS );
		oddout_catalog_record_source( 'transient', $local );

		$remote = array(
			'version' => 1,
			'bundles' => array(
				$this->catalog_row( 'new-widget' ),
			),
		);
		add_filter(
			'pre_http_request',
			static function () use ( $remote ) {
				return array(
					'headers'  => array(),
					'body'     => wp_json_encode( $remote ),
					'response' => array(
						'code'    => 200,
						'message' => 'OK',
					),
				);
			}
		);

		$user = self::factory()->user->create( array( 'role' => 'administrator' ) );
		wp_set_current_user( $user );

		global $wp_rest_server;
		$wp_rest_server = new WP_REST_Server();
		do_action( 'rest_api_init' );

		$request  = new WP_REST_Request( 'POST', '/odd/v1/bundles/catalog-check' );
		$response = $wp_rest_server->dispatch( $request );
		$data     = $response->get_data();

		$this->assertSame( 200, $response->get_status() );
		$this->assertTrue( $data['checked'] );
		$this->assertTrue( $data['update_available'] );
		$this->assertTrue( $data['meta']['remote_update_available'] );

		$catalog = oddout_bundle_catalog();
		$this->assertSame( 'old-widget', $catalog[0]['slug'], 'Checking must not replace the locally cached catalog.' );
	}

	public function test_remote_catalog_rejects_insecure_registry_url() {
		$result = oddout_catalog_fetch_remote( 'http://example.com/catalog/v1/registry.json' );
		$this->assertWPError( $result );
		$this->assertSame( 'insecure_catalog_url', $result->get_error_code() );
	}

	public function test_first_party_catalog_requires_valid_signature() {
		if ( ! function_exists( 'sodium_crypto_sign_keypair' ) ) {
			$this->markTestSkipped( 'Sodium is required for catalog signature tests.' );
		}

		remove_all_filters( 'oddout_catalog_signature_required' );
		add_filter( 'oddout_catalog_signature_required', '__return_true' );

		$keypair = sodium_crypto_sign_keypair();
		$secret  = sodium_crypto_sign_secretkey( $keypair );
		$public  = sodium_crypto_sign_publickey( $keypair );
		add_filter(
			'oddout_catalog_public_keys',
			static function () use ( $public ) {
				return array( base64_encode( $public ) );
			}
		);

		$raw  = array(
			'version' => 1,
			'bundles' => array( $this->catalog_row( 'signed-widget' ) ),
		);
		$body = wp_json_encode( $raw );
		$sig  = base64_encode( sodium_crypto_sign_detached( $body, $secret ) );
		add_filter(
			'pre_http_request',
			static function ( $preempt, $args, $url ) use ( $body, $sig ) {
				return array(
					'headers'  => array(),
					'body'     => false !== strpos( $url, 'registry.json.sig' ) ? $sig : $body,
					'response' => array(
						'code'    => 200,
						'message' => 'OK',
					),
				);
			},
			10,
			3
		);

		$registry = oddout_catalog_load( true );
		$this->assertSame( 'signed-widget', $registry['bundles'][0]['slug'] );
		$meta = oddout_catalog_meta();
		$this->assertSame( 'remote', $meta['source'] );
		$this->assertSame( 'valid', $meta['signature_status'] );
		$this->assertNotEmpty( $meta['signature_key'] );
	}

	public function test_bad_signature_preserves_stale_catalog() {
		if ( ! function_exists( 'sodium_crypto_sign_keypair' ) ) {
			$this->markTestSkipped( 'Sodium is required for catalog signature tests.' );
		}

		$stale = oddout_catalog_stamp_accepted_registry(
			oddout_catalog_normalise(
				array(
					'version' => 1,
					'bundles' => array( $this->catalog_row( 'signed-stale' ) ),
				)
			)
		);
		update_option( ODDOUT_CATALOG_STALE_OPTION, $stale, false );
		remove_all_filters( 'oddout_catalog_signature_required' );
		add_filter( 'oddout_catalog_signature_required', '__return_true' );

		$keypair = sodium_crypto_sign_keypair();
		$public  = sodium_crypto_sign_publickey( $keypair );
		add_filter(
			'oddout_catalog_public_keys',
			static function () use ( $public ) {
				return array( base64_encode( $public ) );
			}
		);

		$body = wp_json_encode(
			array(
				'version' => 1,
				'bundles' => array( $this->catalog_row( 'bad-signature-widget' ) ),
			)
		);
		$sig  = base64_encode( str_repeat( 'x', 64 ) );
		add_filter(
			'pre_http_request',
			static function ( $preempt, $args, $url ) use ( $body, $sig ) {
				return array(
					'headers'  => array(),
					'body'     => false !== strpos( $url, 'registry.json.sig' ) ? $sig : $body,
					'response' => array(
						'code'    => 200,
						'message' => 'OK',
					),
				);
			},
			10,
			3
		);

		$registry = oddout_catalog_load( true );
		$this->assertSame( 'signed-stale', $registry['bundles'][0]['slug'] );
		$meta = oddout_catalog_meta();
		$this->assertSame( 'stale_option', $meta['source'] );
		$this->assertSame( 'catalog_signature_mismatch', $meta['last_error_code'] );
		$this->assertSame( 'mismatch', $meta['signature_status'] );
	}

	public function test_missing_signature_rejects_first_party_catalog() {
		remove_all_filters( 'oddout_catalog_signature_required' );
		add_filter( 'oddout_catalog_signature_required', '__return_true' );
		$body = wp_json_encode(
			array(
				'version' => 1,
				'bundles' => array( $this->catalog_row( 'missing-signature-widget' ) ),
			)
		);
		add_filter(
			'pre_http_request',
			static function ( $preempt, $args, $url ) use ( $body ) {
				return array(
					'headers'  => array(),
					'body'     => false !== strpos( $url, 'registry.json.sig' ) ? '' : $body,
					'response' => array(
						'code'    => false !== strpos( $url, 'registry.json.sig' ) ? 404 : 200,
						'message' => false !== strpos( $url, 'registry.json.sig' ) ? 'Not Found' : 'OK',
					),
				);
			},
			10,
			3
		);

		$result = oddout_catalog_fetch_remote( ODDOUT_CATALOG_URL );
		$this->assertWPError( $result );
		$this->assertSame( 'catalog_signature_status', $result->get_error_code() );
		$this->assertSame( 'missing', $result->get_error_data()['signature_status'] );
	}

	public function test_private_unsigned_mirror_can_opt_out_of_signatures() {
		$url = 'https://mirror.example.com/catalog/v1/registry.json';
		add_filter(
			'oddout_catalog_url',
			static function () use ( $url ) {
				return $url;
			}
		);
		add_filter( 'oddout_catalog_signature_required', '__return_false' );
		add_filter( 'oddout_catalog_entry_url_allowed', '__return_true' );
		$body          = wp_json_encode(
			array(
				'version' => 1,
				'bundles' => array( $this->catalog_row( 'private-widget' ) ),
			)
		);
		$signature_hit = false;
		add_filter(
			'pre_http_request',
			static function ( $preempt, $args, $request_url ) use ( $body, &$signature_hit ) {
				if ( false !== strpos( $request_url, 'registry.json.sig' ) ) {
					$signature_hit = true;
				}
				return array(
					'headers'  => array(),
					'body'     => $body,
					'response' => array(
						'code'    => 200,
						'message' => 'OK',
					),
				);
			},
			10,
			3
		);

		$registry = oddout_catalog_load( true );
		$this->assertSame( 'private-widget', $registry['bundles'][0]['slug'] );
		$this->assertFalse( $signature_hit );
		$this->assertSame( 'skipped', oddout_catalog_meta()['signature_status'] );
	}

	public function test_record_source_preserves_known_signature_status_for_unsigned_runtime_sources() {
		oddout_catalog_update_meta(
			array(
				'signature_status' => 'valid',
			)
		);

		$registry                             = oddout_catalog_normalise(
			array(
				'version' => 1,
				'bundles' => array( $this->catalog_row( 'fallback-widget' ) ),
			)
		);
		$registry['_oddout_signature_status'] = 'unknown';

		oddout_catalog_record_source( 'fallback_file', $registry );
		$this->assertSame( 'valid', oddout_catalog_meta()['signature_status'] );
	}

	public function test_remote_acceptance_saves_previous_stale_for_rollback_restore() {
		$previous = oddout_catalog_stamp_accepted_registry(
			oddout_catalog_normalise(
				array(
					'version' => 1,
					'bundles' => array( $this->catalog_row( 'previous-widget' ) ),
				)
			)
		);
		update_option( ODDOUT_CATALOG_STALE_OPTION, $previous, false );

		$raw = array(
			'version' => 1,
			'bundles' => array( $this->catalog_row( 'new-widget' ) ),
		);
		add_filter(
			'pre_http_request',
			static function () use ( $raw ) {
				return array(
					'headers'  => array(),
					'body'     => wp_json_encode( $raw ),
					'response' => array(
						'code'    => 200,
						'message' => 'OK',
					),
				);
			}
		);

		$loaded = oddout_catalog_load( true );
		$this->assertSame( 'new-widget', $loaded['bundles'][0]['slug'] );
		$this->assertTrue( oddout_catalog_meta()['rollback_available'] );

		$restored = oddout_catalog_restore_previous_snapshot();
		$this->assertIsArray( $restored );
		$this->assertSame( 'previous-widget', $restored['bundles'][0]['slug'] );
		$mirror = get_option( ODDOUT_CATALOG_STALE_OPTION );
		$this->assertSame( 'previous-widget', $mirror['bundles'][0]['slug'] );
		$meta = oddout_catalog_meta();
		$this->assertSame( 'rollback_option', $meta['source'] );
		$this->assertTrue( $meta['rollback_available'] );
	}

	public function test_requires_rows_stay_visible_but_cannot_install_or_seed_starter_pack() {
		add_filter(
			'oddout_catalog_current_versions',
			static function () {
				return array(
					'odd'         => '1.0.0',
					'desktopMode' => '0.8.5',
					'api'         => '2.3.0',
				);
			}
		);
		$raw = array(
			'version'      => 1,
			'starter_pack' => array(
				'widgets' => array( 'future-widget', 'current-widget' ),
			),
			'bundles'      => array(
				$this->catalog_row(
					'future-widget',
					array(
						'requires' => array( 'odd' => '99.0.0' ),
					)
				),
				$this->catalog_row( 'current-widget' ),
			),
		);
		add_filter(
			'pre_http_request',
			static function () use ( $raw ) {
				return array(
					'headers'  => array(),
					'body'     => wp_json_encode( $raw ),
					'response' => array(
						'code'    => 200,
						'message' => 'OK',
					),
				);
			}
		);

		$registry = oddout_catalog_load( true );
		$future   = null;
		foreach ( $registry['bundles'] as $row ) {
			if ( isset( $row['slug'] ) && 'future-widget' === $row['slug'] ) {
				$future = $row;
				break;
			}
		}
		$this->assertIsArray( $future );
		$this->assertTrue( $future['incompatible'] );
		$this->assertSame( 'incompatible', $future['state'] );
		$this->assertSame( array( 'current-widget' ), $registry['starter_pack']['widgets'] );

		$user = self::factory()->user->create( array( 'role' => 'administrator' ) );
		wp_set_current_user( $user );
		global $wp_rest_server;
		$wp_rest_server = new WP_REST_Server();
		do_action( 'rest_api_init' );

		$request = new WP_REST_Request( 'POST', '/odd/v1/bundles/install-from-catalog' );
		$request->set_param( 'slug', 'future-widget' );
		$response = $wp_rest_server->dispatch( $request );
		$data     = $response->get_data();
		$this->assertSame( 409, $response->get_status() );
		$this->assertSame( 'catalog_incompatible', $data['code'] );
	}

	public function test_remote_catalog_rejects_duplicate_slugs() {
		$raw = array(
			'version' => 1,
			'bundles' => array(
				$this->catalog_row( 'duplicate' ),
				$this->catalog_row( 'duplicate', array( 'name' => 'Duplicate Two' ) ),
			),
		);
		add_filter(
			'pre_http_request',
			static function () use ( $raw ) {
				return array(
					'headers'  => array(),
					'body'     => wp_json_encode( $raw ),
					'response' => array(
						'code'    => 200,
						'message' => 'OK',
					),
				);
			}
		);

		$result = oddout_catalog_fetch_remote( ODDOUT_CATALOG_URL );
		$this->assertWPError( $result );
		$this->assertSame( 'catalog_duplicate_slug', $result->get_error_code() );
	}

	public function test_remote_catalog_rejects_bad_version_size_and_starter_refs() {
		$bad_version = oddout_catalog_validate_remote_registry(
			array(
				'version' => 2,
				'bundles' => array(),
			),
			ODDOUT_CATALOG_URL
		);
		$this->assertWPError( $bad_version );
		$this->assertSame( 'catalog_bad_version', $bad_version->get_error_code() );

		$missing_size_row = $this->catalog_row( 'missing-size' );
		unset( $missing_size_row['size'] );
		$missing_size = oddout_catalog_validate_remote_registry(
			array(
				'version' => 1,
				'bundles' => array( $missing_size_row ),
			),
			ODDOUT_CATALOG_URL
		);
		$this->assertWPError( $missing_size );
		$this->assertSame( 'catalog_bad_size', $missing_size->get_error_code() );

		$bad_starter = oddout_catalog_validate_remote_registry(
			array(
				'version'      => 1,
				'starter_pack' => array(
					'scenes' => array( 'starter-widget' ),
				),
				'bundles'      => array(
					$this->catalog_row( 'starter-widget' ),
				),
			),
			ODDOUT_CATALOG_URL
		);
		$this->assertWPError( $bad_starter );
		$this->assertSame( 'catalog_bad_starter_pack_slug', $bad_starter->get_error_code() );
	}

	public function test_remote_catalog_rejects_bad_hash_and_external_urls() {
		$bad_hash = oddout_catalog_validate_remote_registry(
			array(
				'version' => 1,
				'bundles' => array(
					$this->catalog_row( 'bad-hash', array( 'sha256' => 'nope' ) ),
				),
			),
			ODDOUT_CATALOG_URL
		);
		$this->assertWPError( $bad_hash );
		$this->assertSame( 'catalog_bad_hash', $bad_hash->get_error_code() );

		$external = oddout_catalog_validate_remote_registry(
			array(
				'version' => 1,
				'bundles' => array(
					$this->catalog_row(
						'external',
						array( 'download_url' => 'https://cdn.example.com/widget-external.wp' )
					),
				),
			),
			ODDOUT_CATALOG_URL
		);
		$this->assertWPError( $external );
		$this->assertSame( 'catalog_unsafe_url', $external->get_error_code() );
	}

	public function test_remote_catalog_caps_body_size_and_records_body_hash() {
		add_filter(
			'oddout_catalog_max_response_bytes',
			static function () {
				return 1024;
			}
		);
		add_filter(
			'pre_http_request',
			static function () {
				return array(
					'headers'  => array(),
					'body'     => str_repeat( 'x', 1200 ),
					'response' => array(
						'code'    => 200,
						'message' => 'OK',
					),
				);
			}
		);
		$too_large = oddout_catalog_fetch_remote( ODDOUT_CATALOG_URL );
		$this->assertWPError( $too_large );
		$this->assertSame( 'catalog_body_too_large', $too_large->get_error_code() );

		remove_all_filters( 'oddout_catalog_max_response_bytes' );
		remove_all_filters( 'pre_http_request' );

		$raw  = array(
			'version' => 1,
			'bundles' => array( $this->catalog_row( 'hashable' ) ),
		);
		$body = wp_json_encode( $raw );
		add_filter(
			'pre_http_request',
			static function () use ( $body ) {
				return array(
					'headers'  => array(),
					'body'     => $body,
					'response' => array(
						'code'    => 200,
						'message' => 'OK',
					),
				);
			}
		);

		oddout_catalog_load( true );
		$meta = oddout_catalog_meta();
		$this->assertSame( hash( 'sha256', $body ), $meta['registry_sha256'] );
		$this->assertSame( strlen( $body ), $meta['registry_bytes'] );
	}

	public function test_catalog_lock_suppresses_duplicate_operations_until_stale() {
		$key = 'oddout_catalog_test_lock';
		delete_option( $key );

		$this->assertTrue( oddout_catalog_lock_acquire( $key, 60 ) );
		$second = oddout_catalog_lock_acquire( $key, 60 );
		$this->assertWPError( $second );
		$this->assertSame( 'catalog_operation_in_progress', $second->get_error_code() );

		update_option( $key, (string) ( time() - 120 ), false );
		$this->assertTrue( oddout_catalog_lock_acquire( $key, 60 ) );
		oddout_catalog_lock_release( $key );
	}
}
