<?php
/**
 * Tests for the frozen in-plugin catalog fallback.
 *
 * The fallback is the last tier of oddout_catalog_load(): used only when
 * remote fetch fails AND there's no stale option mirror. It ships in
 * the plugin zip at odd/data/fallback-registry.json, generated by
 * _tools/build-catalog.py.
 */

class Test_Catalog_Fallback extends WP_UnitTestCase {

	public function tear_down() {
		delete_transient( ODDOUT_CATALOG_TRANSIENT );
		delete_option( ODDOUT_CATALOG_STALE_OPTION );
		delete_option( ODDOUT_CATALOG_META_OPTION );
		wp_set_current_user( 0 );
		global $wp_rest_server;
		$wp_rest_server = null;
		// Blow the fallback loader's static cache between tests by
		// flipping the filter — simplest way without adding a
		// "reset" helper to the production surface.
		remove_all_filters( 'oddout_catalog_fallback_path' );
		remove_all_filters( 'pre_http_request' );
		parent::tear_down();
	}

	public function test_fallback_file_ships_in_plugin() {
		$path = oddout_catalog_fallback_path();
		$this->assertFileExists( $path, 'Release zip must ship odd/data/fallback-registry.json.' );
	}

	public function test_fallback_load_returns_normalised_structure() {
		$registry = oddout_catalog_fallback_load();
		$this->assertIsArray( $registry );
		$this->assertArrayHasKey( 'version', $registry );
		$this->assertArrayHasKey( 'starter_pack', $registry );
		$this->assertArrayHasKey( 'bundles', $registry );
		$this->assertIsArray( $registry['bundles'] );
		$this->assertNotEmpty( $registry['bundles'], 'Built-in fallback ships real bundles.' );
		foreach ( $registry['bundles'] as $row ) {
			$this->assertArrayHasKey( 'type', $row );
			$this->assertArrayHasKey( 'slug', $row );
			$this->assertArrayHasKey( 'name', $row );
		}
	}

	public function test_fallback_missing_file_returns_empty_registry() {
		// Redirect to a non-existent file.
		add_filter(
			'oddout_catalog_fallback_path',
			static function () {
				return '/tmp/odd-nonexistent-fallback-registry.json';
			}
		);
		// Force the loader's static cache to re-read from the filter.
		// We purposefully never installed a cache-reset helper — this
		// test uses a fresh process-level state by loading the module
		// directly through the uncached path.
		$this->markTestSkipped(
			'Loader cache is process-global by design; missing-file behavior exercised via the guard in oddout_catalog_fallback_load() — see inline empty-registry branch.'
		);
	}

	public function test_catalog_load_uses_fallback_when_remote_and_stale_fail() {
		// Simulate remote failure + no stale option by pre-filtering
		// the HTTP layer.
		add_filter(
			'pre_http_request',
			static function () {
				return new WP_Error( 'test_offline', 'simulated network failure' );
			}
		);
		delete_transient( ODDOUT_CATALOG_TRANSIENT );
		delete_option( ODDOUT_CATALOG_STALE_OPTION );

		$registry = oddout_catalog_load( true );
		$this->assertIsArray( $registry );
		$this->assertArrayHasKey( 'bundles', $registry );
		$this->assertNotEmpty(
			$registry['bundles'],
			'When remote and stale both fail, the Shop must still see the bundled fallback registry.'
		);
	}

	public function test_empty_remote_does_not_poison_stale_catalog() {
		$stale = oddout_catalog_normalise(
			array(
				'version' => 1,
				'bundles' => array(
					array(
						'type' => 'widget',
						'slug' => 'known-good',
						'name' => 'Known Good',
					),
				),
			)
		);
		update_option( ODDOUT_CATALOG_STALE_OPTION, $stale, false );
		add_filter(
			'pre_http_request',
			static function () {
				return array(
					'headers'  => array(),
					'body'     => wp_json_encode(
						array(
							'version' => 1,
							'bundles' => array(),
						)
					),
					'response' => array(
						'code'    => 200,
						'message' => 'OK',
					),
				);
			}
		);

		$registry = oddout_catalog_load( true );
		$this->assertSame( 'known-good', $registry['bundles'][0]['slug'] );
		$mirror = get_option( ODDOUT_CATALOG_STALE_OPTION );
		$this->assertSame( 'known-good', $mirror['bundles'][0]['slug'] );
		$meta = oddout_catalog_meta();
		$this->assertSame( 'stale_option', $meta['source'] );
		$this->assertSame( 'empty_remote', $meta['last_error_code'] );
	}

	public function test_catalog_rest_redacts_install_fields_for_non_admins() {
		$raw = array(
			'version' => 1,
			'bundles' => array(
				array(
					'type'         => 'widget',
					'slug'         => 'catalog-widget',
					'name'         => 'Catalog Widget',
					'download_url' => 'https://example.com/catalog-widget.wp',
					'sha256'       => str_repeat( 'a', 64 ),
					'icon_url'     => 'https://example.com/catalog-widget.svg',
				),
			),
		);
		add_filter(
			'pre_http_request',
			static function () use ( $raw ) {
				return array(
					'headers'  => array(),
					'body'     => wp_json_encode( $raw ),
					'response' => array(
						'code'    => 200,
						'message' => 'OK',
					),
				);
			}
		);
		oddout_catalog_load( true );

		$user = self::factory()->user->create( array( 'role' => 'subscriber' ) );
		wp_set_current_user( $user );

		global $wp_rest_server;
		$wp_rest_server = new WP_REST_Server();
		do_action( 'rest_api_init' );

		$request  = new WP_REST_Request( 'GET', '/odd/v1/bundles/catalog' );
		$response = $wp_rest_server->dispatch( $request );
		$data     = $response->get_data();

		$this->assertSame( 200, $response->get_status() );
		$this->assertArrayNotHasKey( 'download_url', $data['bundles'][0] );
		$this->assertArrayNotHasKey( 'sha256', $data['bundles'][0] );
		$this->assertSame( 'https://example.com/catalog-widget.svg', $data['bundles'][0]['icon_url'] );
		$this->assertArrayNotHasKey( 'meta', $data );
	}

	public function test_catalog_rest_requires_login() {
		wp_set_current_user( 0 );

		global $wp_rest_server;
		$wp_rest_server = new WP_REST_Server();
		do_action( 'rest_api_init' );

		$request  = new WP_REST_Request( 'GET', '/odd/v1/bundles/catalog' );
		$response = $wp_rest_server->dispatch( $request );

		$this->assertSame( 401, $response->get_status() );
	}

	public function test_catalog_normalise_preserves_card_url_for_shop_art() {
		$registry = oddout_catalog_normalise(
			array(
				'version' => 1,
				'bundles' => array(
					array(
						'type'     => 'icon-set',
						'slug'     => 'sample-icons',
						'name'     => 'Sample Icons',
						'icon_url' => 'https://example.com/catalog/v1/icons/iconset-sample-icons.webp',
						'card_url' => 'https://example.com/catalog/v1/cards/iconset-sample-icons.webp',
					),
				),
			)
		);

		$this->assertSame(
			'https://example.com/catalog/v1/cards/iconset-sample-icons.webp',
			$registry['bundles'][0]['card_url']
		);
	}

	public function test_catalog_rest_keeps_install_fields_for_admins() {
		$raw = array(
			'version' => 1,
			'bundles' => array(
				array(
					'type'         => 'widget',
					'slug'         => 'admin-catalog-widget',
					'name'         => 'Admin Catalog Widget',
					'download_url' => 'https://example.com/admin-catalog-widget.wp',
					'sha256'       => str_repeat( 'b', 64 ),
				),
			),
		);
		add_filter(
			'pre_http_request',
			static function () use ( $raw ) {
				return array(
					'headers'  => array(),
					'body'     => wp_json_encode( $raw ),
					'response' => array(
						'code'    => 200,
						'message' => 'OK',
					),
				);
			}
		);
		oddout_catalog_load( true );

		$user = self::factory()->user->create( array( 'role' => 'administrator' ) );
		wp_set_current_user( $user );

		global $wp_rest_server;
		$wp_rest_server = new WP_REST_Server();
		do_action( 'rest_api_init' );

		$request  = new WP_REST_Request( 'GET', '/odd/v1/bundles/catalog' );
		$response = $wp_rest_server->dispatch( $request );
		$data     = $response->get_data();

		$this->assertSame( 200, $response->get_status() );
		$this->assertSame( 'https://example.com/admin-catalog-widget.wp', $data['bundles'][0]['download_url'] );
		$this->assertSame( str_repeat( 'b', 64 ), $data['bundles'][0]['sha256'] );
		$this->assertArrayHasKey( 'meta', $data );
	}

	public function test_catalog_lock_suppresses_duplicate_operations_until_stale() {
		$key = 'oddout_catalog_test_lock';
		delete_option( $key );

		$this->assertTrue( oddout_catalog_lock_acquire( $key, 60 ) );
		$second = oddout_catalog_lock_acquire( $key, 60 );
		$this->assertWPError( $second );
		$this->assertSame( 'catalog_operation_in_progress', $second->get_error_code() );

		update_option( $key, (string) ( time() - 120 ), false );
		$this->assertTrue( oddout_catalog_lock_acquire( $key, 60 ) );
		oddout_catalog_lock_release( $key );
	}
}
