<?php
/**
 * Tests for the frozen in-plugin catalog fallback.
 *
 * The fallback is the last tier of oddout_catalog_load(): used only when
 * remote fetch fails AND there's no stale option mirror. It ships in
 * the plugin zip at odd/data/fallback-registry.json, generated by
 * _tools/build-catalog.py.
 */

class Test_Catalog_Fallback extends WP_UnitTestCase {

	private function catalog_row( $slug, $overrides = array() ) {
		$base = 'https://odd.regionallyfamous.com/catalog/v1/';
		return array_merge(
			array(
				'type'         => 'widget',
				'slug'         => $slug,
				'name'         => ucwords( str_replace( '-', ' ', $slug ) ),
				'version'      => '1.0.0',
				'download_url' => $base . 'bundles/widget-' . $slug . '.wp',
				'sha256'       => str_repeat( 'a', 64 ),
				'icon_url'     => $base . 'icons/widget-' . $slug . '.svg',
				'card_url'     => $base . 'cards/widget-' . $slug . '.webp',
			),
			$overrides
		);
	}

	public function tear_down() {
		delete_transient( ODDOUT_CATALOG_TRANSIENT );
		delete_option( ODDOUT_CATALOG_STALE_OPTION );
		delete_option( ODDOUT_CATALOG_META_OPTION );
		wp_set_current_user( 0 );
		global $wp_rest_server;
		$wp_rest_server = null;
		// Blow the fallback loader's static cache between tests by
		// flipping the filter — simplest way without adding a
		// "reset" helper to the production surface.
		remove_all_filters( 'oddout_catalog_fallback_path' );
		remove_all_filters( 'oddout_catalog_entry_url_allowed' );
		remove_all_filters( 'oddout_catalog_max_response_bytes' );
		remove_all_filters( 'oddout_catalog_url' );
		remove_all_filters( 'pre_http_request' );
		parent::tear_down();
	}

	public function test_fallback_file_ships_in_plugin() {
		$path = oddout_catalog_fallback_path();
		$this->assertFileExists( $path, 'Release zip must ship odd/data/fallback-registry.json.' );
	}

	public function test_fallback_load_returns_normalised_structure() {
		$registry = oddout_catalog_fallback_load();
		$this->assertIsArray( $registry );
		$this->assertArrayHasKey( 'version', $registry );
		$this->assertArrayHasKey( 'starter_pack', $registry );
		$this->assertArrayHasKey( 'bundles', $registry );
		$this->assertIsArray( $registry['bundles'] );
		$this->assertNotEmpty( $registry['bundles'], 'Built-in fallback ships real bundles.' );
		foreach ( $registry['bundles'] as $row ) {
			$this->assertArrayHasKey( 'type', $row );
			$this->assertArrayHasKey( 'slug', $row );
			$this->assertArrayHasKey( 'name', $row );
		}
	}

	public function test_fallback_missing_file_returns_empty_registry() {
		// Redirect to a non-existent file.
		add_filter(
			'oddout_catalog_fallback_path',
			static function () {
				return '/tmp/odd-nonexistent-fallback-registry.json';
			}
		);
		// Force the loader's static cache to re-read from the filter.
		// We purposefully never installed a cache-reset helper — this
		// test uses a fresh process-level state by loading the module
		// directly through the uncached path.
		$this->markTestSkipped(
			'Loader cache is process-global by design; missing-file behavior exercised via the guard in oddout_catalog_fallback_load() — see inline empty-registry branch.'
		);
	}

	public function test_catalog_load_uses_fallback_when_remote_and_stale_fail() {
		// Simulate remote failure + no stale option by pre-filtering
		// the HTTP layer.
		add_filter(
			'pre_http_request',
			static function () {
				return new WP_Error( 'test_offline', 'simulated network failure' );
			}
		);
		delete_transient( ODDOUT_CATALOG_TRANSIENT );
		delete_option( ODDOUT_CATALOG_STALE_OPTION );

		$registry = oddout_catalog_load( true );
		$this->assertIsArray( $registry );
		$this->assertArrayHasKey( 'bundles', $registry );
		$this->assertNotEmpty(
			$registry['bundles'],
			'When remote and stale both fail, the Shop must still see the bundled fallback registry.'
		);
	}

	public function test_empty_remote_does_not_poison_stale_catalog() {
		$stale = oddout_catalog_normalise(
			array(
				'version' => 1,
				'bundles' => array(
					$this->catalog_row( 'known-good' ),
				),
			)
		);
		update_option( ODDOUT_CATALOG_STALE_OPTION, $stale, false );
		add_filter(
			'pre_http_request',
			static function () {
				return array(
					'headers'  => array(),
					'body'     => wp_json_encode(
						array(
							'version' => 1,
							'bundles' => array(),
						)
					),
					'response' => array(
						'code'    => 200,
						'message' => 'OK',
					),
				);
			}
		);

		$registry = oddout_catalog_load( true );
		$this->assertSame( 'known-good', $registry['bundles'][0]['slug'] );
		$mirror = get_option( ODDOUT_CATALOG_STALE_OPTION );
		$this->assertSame( 'known-good', $mirror['bundles'][0]['slug'] );
		$meta = oddout_catalog_meta();
		$this->assertSame( 'stale_option', $meta['source'] );
		$this->assertSame( 'empty_remote', $meta['last_error_code'] );
	}

	public function test_catalog_rest_redacts_install_fields_for_non_admins() {
		$raw = array(
			'version' => 1,
			'bundles' => array(
				$this->catalog_row( 'catalog-widget' ),
			),
		);
		add_filter(
			'pre_http_request',
			static function () use ( $raw ) {
				return array(
					'headers'  => array(),
					'body'     => wp_json_encode( $raw ),
					'response' => array(
						'code'    => 200,
						'message' => 'OK',
					),
				);
			}
		);
		oddout_catalog_load( true );

		$user = self::factory()->user->create( array( 'role' => 'subscriber' ) );
		wp_set_current_user( $user );

		global $wp_rest_server;
		$wp_rest_server = new WP_REST_Server();
		do_action( 'rest_api_init' );

		$request  = new WP_REST_Request( 'GET', '/odd/v1/bundles/catalog' );
		$response = $wp_rest_server->dispatch( $request );
		$data     = $response->get_data();

		$this->assertSame( 200, $response->get_status() );
		$this->assertArrayNotHasKey( 'download_url', $data['bundles'][0] );
		$this->assertArrayNotHasKey( 'sha256', $data['bundles'][0] );
		$this->assertSame( 'https://odd.regionallyfamous.com/catalog/v1/icons/widget-catalog-widget.svg', $data['bundles'][0]['icon_url'] );
		$this->assertArrayNotHasKey( 'meta', $data );
	}

	public function test_catalog_rest_requires_login() {
		wp_set_current_user( 0 );

		global $wp_rest_server;
		$wp_rest_server = new WP_REST_Server();
		do_action( 'rest_api_init' );

		$request  = new WP_REST_Request( 'GET', '/odd/v1/bundles/catalog' );
		$response = $wp_rest_server->dispatch( $request );

		$this->assertSame( 401, $response->get_status() );
	}

	public function test_catalog_rest_rejects_unknown_type_arg() {
		$user = self::factory()->user->create( array( 'role' => 'subscriber' ) );
		wp_set_current_user( $user );

		global $wp_rest_server;
		$wp_rest_server = new WP_REST_Server();
		do_action( 'rest_api_init' );

		$request = new WP_REST_Request( 'GET', '/odd/v1/bundles/catalog' );
		$request->set_param( 'type', 'plugin' );
		$response = $wp_rest_server->dispatch( $request );

		$this->assertSame( 400, $response->get_status() );
	}

	public function test_catalog_install_rest_requires_slug_arg() {
		$user = self::factory()->user->create( array( 'role' => 'administrator' ) );
		wp_set_current_user( $user );

		global $wp_rest_server;
		$wp_rest_server = new WP_REST_Server();
		do_action( 'rest_api_init' );

		$request  = new WP_REST_Request( 'POST', '/odd/v1/bundles/install-from-catalog' );
		$response = $wp_rest_server->dispatch( $request );

		$this->assertSame( 400, $response->get_status() );
	}

	public function test_catalog_normalise_preserves_card_url_for_shop_art() {
		$registry = oddout_catalog_normalise(
			array(
				'version' => 1,
				'bundles' => array(
					array(
						'type'     => 'icon-set',
						'slug'     => 'sample-icons',
						'name'     => 'Sample Icons',
						'icon_url' => 'https://example.com/catalog/v1/icons/iconset-sample-icons.webp',
						'card_url' => 'https://example.com/catalog/v1/cards/iconset-sample-icons.webp',
					),
				),
			)
		);

		$this->assertSame(
			'https://example.com/catalog/v1/cards/iconset-sample-icons.webp',
			$registry['bundles'][0]['card_url']
		);
	}

	public function test_catalog_normalise_drops_legacy_svg_icon_sets() {
		$registry = oddout_catalog_normalise(
			array(
				'version'      => 1,
				'starter_pack' => array(
					'iconSets' => array( 'legacy-icons', 'modern-icons' ),
				),
				'bundles'      => array(
					$this->catalog_row(
						'legacy-icons',
						array(
							'type'     => 'icon-set',
							'icon_url' => 'https://odd.regionallyfamous.com/catalog/v1/icons/iconset-legacy-icons.svg',
						)
					),
					$this->catalog_row(
						'modern-icons',
						array(
							'type'     => 'icon-set',
							'icon_url' => 'https://odd.regionallyfamous.com/catalog/v1/icons/iconset-modern-icons.webp',
						)
					),
					$this->catalog_row( 'still-valid-widget' ),
				),
			)
		);

		$slugs = wp_list_pluck( $registry['bundles'], 'slug' );
		$this->assertNotContains( 'legacy-icons', $slugs );
		$this->assertContains( 'modern-icons', $slugs );
		$this->assertContains( 'still-valid-widget', $slugs );
		$this->assertSame( array( 'modern-icons' ), $registry['starter_pack']['iconSets'] );
	}

	public function test_catalog_merges_fallback_icon_sets_when_remote_icon_sets_are_legacy() {
		$registry = oddout_catalog_normalise(
			array(
				'version'      => 1,
				'starter_pack' => array(
					'iconSets' => array( 'legacy-icons' ),
				),
				'bundles'      => array(
					$this->catalog_row(
						'legacy-icons',
						array(
							'type'     => 'icon-set',
							'icon_url' => 'https://odd.regionallyfamous.com/catalog/v1/icons/iconset-legacy-icons.svg',
						)
					),
					$this->catalog_row( 'still-valid-widget' ),
				),
			)
		);
		$merged   = oddout_catalog_merge_fallback_icon_sets( $registry );
		$iconsets = array_values(
			array_filter(
				$merged['bundles'],
				static function ( $row ) {
					return is_array( $row ) && isset( $row['type'] ) && 'icon-set' === $row['type'];
				}
			)
		);

		$this->assertNotEmpty( $iconsets );
		$this->assertSame( 'oddlings', $iconsets[0]['slug'] );
		$this->assertStringEndsWith( '.webp', $iconsets[0]['icon_url'] );
		$this->assertSame( array( 'oddlings' ), $merged['starter_pack']['iconSets'] );
	}

	public function test_catalog_rest_keeps_install_fields_for_admins() {
		$raw = array(
			'version' => 1,
			'bundles' => array(
				$this->catalog_row(
					'admin-catalog-widget',
					array(
						'sha256' => str_repeat( 'b', 64 ),
					)
				),
			),
		);
		add_filter(
			'pre_http_request',
			static function () use ( $raw ) {
				return array(
					'headers'  => array(),
					'body'     => wp_json_encode( $raw ),
					'response' => array(
						'code'    => 200,
						'message' => 'OK',
					),
				);
			}
		);
		oddout_catalog_load( true );

		$user = self::factory()->user->create( array( 'role' => 'administrator' ) );
		wp_set_current_user( $user );

		global $wp_rest_server;
		$wp_rest_server = new WP_REST_Server();
		do_action( 'rest_api_init' );

		$request  = new WP_REST_Request( 'GET', '/odd/v1/bundles/catalog' );
		$response = $wp_rest_server->dispatch( $request );
		$data     = $response->get_data();

		$this->assertSame( 200, $response->get_status() );
		$this->assertSame( 'https://odd.regionallyfamous.com/catalog/v1/bundles/widget-admin-catalog-widget.wp', $data['bundles'][0]['download_url'] );
		$this->assertSame( str_repeat( 'b', 64 ), $data['bundles'][0]['sha256'] );
		$this->assertArrayHasKey( 'meta', $data );
	}

	public function test_remote_catalog_rejects_insecure_registry_url() {
		$result = oddout_catalog_fetch_remote( 'http://example.com/catalog/v1/registry.json' );
		$this->assertWPError( $result );
		$this->assertSame( 'insecure_catalog_url', $result->get_error_code() );
	}

	public function test_remote_catalog_rejects_duplicate_slugs() {
		$raw = array(
			'version' => 1,
			'bundles' => array(
				$this->catalog_row( 'duplicate' ),
				$this->catalog_row( 'duplicate', array( 'name' => 'Duplicate Two' ) ),
			),
		);
		add_filter(
			'pre_http_request',
			static function () use ( $raw ) {
				return array(
					'headers'  => array(),
					'body'     => wp_json_encode( $raw ),
					'response' => array(
						'code'    => 200,
						'message' => 'OK',
					),
				);
			}
		);

		$result = oddout_catalog_fetch_remote( ODDOUT_CATALOG_URL );
		$this->assertWPError( $result );
		$this->assertSame( 'catalog_duplicate_slug', $result->get_error_code() );
	}

	public function test_remote_catalog_rejects_bad_hash_and_external_urls() {
		$bad_hash = oddout_catalog_validate_remote_registry(
			array(
				'version' => 1,
				'bundles' => array(
					$this->catalog_row( 'bad-hash', array( 'sha256' => 'nope' ) ),
				),
			),
			ODDOUT_CATALOG_URL
		);
		$this->assertWPError( $bad_hash );
		$this->assertSame( 'catalog_bad_hash', $bad_hash->get_error_code() );

		$external = oddout_catalog_validate_remote_registry(
			array(
				'version' => 1,
				'bundles' => array(
					$this->catalog_row(
						'external',
						array( 'download_url' => 'https://cdn.example.com/widget-external.wp' )
					),
				),
			),
			ODDOUT_CATALOG_URL
		);
		$this->assertWPError( $external );
		$this->assertSame( 'catalog_unsafe_url', $external->get_error_code() );
	}

	public function test_remote_catalog_caps_body_size_and_records_body_hash() {
		add_filter(
			'oddout_catalog_max_response_bytes',
			static function () {
				return 1024;
			}
		);
		add_filter(
			'pre_http_request',
			static function () {
				return array(
					'headers'  => array(),
					'body'     => str_repeat( 'x', 1200 ),
					'response' => array(
						'code'    => 200,
						'message' => 'OK',
					),
				);
			}
		);
		$too_large = oddout_catalog_fetch_remote( ODDOUT_CATALOG_URL );
		$this->assertWPError( $too_large );
		$this->assertSame( 'catalog_body_too_large', $too_large->get_error_code() );

		remove_all_filters( 'oddout_catalog_max_response_bytes' );
		remove_all_filters( 'pre_http_request' );

		$raw  = array(
			'version' => 1,
			'bundles' => array( $this->catalog_row( 'hashable' ) ),
		);
		$body = wp_json_encode( $raw );
		add_filter(
			'pre_http_request',
			static function () use ( $body ) {
				return array(
					'headers'  => array(),
					'body'     => $body,
					'response' => array(
						'code'    => 200,
						'message' => 'OK',
					),
				);
			}
		);

		oddout_catalog_load( true );
		$meta = oddout_catalog_meta();
		$this->assertSame( hash( 'sha256', $body ), $meta['registry_sha256'] );
		$this->assertSame( strlen( $body ), $meta['registry_bytes'] );
	}

	public function test_catalog_lock_suppresses_duplicate_operations_until_stale() {
		$key = 'oddout_catalog_test_lock';
		delete_option( $key );

		$this->assertTrue( oddout_catalog_lock_acquire( $key, 60 ) );
		$second = oddout_catalog_lock_acquire( $key, 60 );
		$this->assertWPError( $second );
		$this->assertSame( 'catalog_operation_in_progress', $second->get_error_code() );

		update_option( $key, (string) ( time() - 120 ), false );
		$this->assertTrue( oddout_catalog_lock_acquire( $key, 60 ) );
		oddout_catalog_lock_release( $key );
	}
}
